
c               Copyright 1993 Colorado State University
c                       All Rights Reserved


      common/parcp/astrec(3),aglrem,astgc,astlbl,astlig,
     &    auirri,awhc,basfc2,bglrem,bioflg,biok5,biomax,clteff(4),
     &    crpgrw,crprtf(3),cultra(7),efrgrn(3),
     &    fallrt,fawhc,fdfrem(4),fdgrem,
     &    fecf(3),feclig,flfrem,flghrv,flgrem,fligni(2,2),fnue(2),
     &    fret(3,4),frtc(4),frtcindx,frtsh,fsdeth(4),fulcan,
     &    gfcret,gret(3),grwprc,grzeff,
     &    hibg,himax,himon(2),hiwsf,irramt,irraut,msplt,pltmrf,
     &    pramn(3,2),pramx(3,2),prbmn(3,2),prbmx(3,2),rdr,rmvstr,
     &    rtdtmp,sdethc,seedl,twhc,vlossp

      integer auirri,bioflg,crpgrw,flghrv,grzeff,himon,msplt,seedl,
     &        frtcindx

      real astrec,aglrem,astgc,astlbl,
     &     astlig,awhc,basfc2,bglrem,biok5,biomax,clteff,crprtf,
     &     cultra,efrgrn,fallrt,fawhc,fdfrem,fdgrem,fecf,feclig,
     &     flfrem,flgrem,fligni,fnue,fret,frtc,frtsh,
     &     fsdeth,fulcan,gfcret,gret,grwprc,hibg,himax,hiwsf,irramt,
     &     irraut,pltmrf,pramn,pramx,prbmn,prbmx,
     &     rdr,rmvstr,rtdtmp,sdethc,twhc,vlossp

      save /parcp/
