
c               Copyright 1993 Colorado State University
c                       All Rights Reserved


      common/parfs/basfct,btolai,ccefor(2,5,3),cerfor(3,5,3),
     &    decid,decw1,decw2,decw3,
     &    fcfrac(5,2),forgrw,forrtf(3),frfrac(2),
     &    klai,laitop,ldrmlt,leafdr(12),
     &    maxlai,maxldr,maxnp,sapk,swold,
     &    wdlig(5),wooddr(5)
C -----------fmyuan: modification for BIOCOMPLEXITY Project ------------
     &    ,twigdr(12)
C -----------fmyuan: modification for BIOCOMPLEXITY Project ------------

      integer decid,forgrw

      real basfct,btolai,ccefor,cerfor,decw1,decw2,decw3,
     &     fcfrac,forrtf,frfrac,klai,laitop,ldrmlt,leafdr,
     &     maxlai,maxldr,maxnp,sapk,swold,
     &     wdlig,wooddr
C -----------fmyuan: modification for BIOCOMPLEXITY Project ------------
     &    ,twigdr
C -----------fmyuan: modification for BIOCOMPLEXITY Project ------------

      save /parfs/
