
c               Copyright 1993 Colorado State University
c                       All Rights Reserved


      common/parfs/basfct,btolai,ccefor(2,5,3),cerfor(3,5,3),
     &    decid,decw1,decw2,decw3,
     &    fcfrac(5,2),forgrw,forrtf(3),
     &    klai,laitop,ldrmlt,leafdr(12),
     &    maxlai,maxldr,maxnp,sapk,swold,tfrtcn(2),tfrtcw(2),
     &    wdlig(5),woodb,wooddr(5)

      integer decid,forgrw

      real basfct,btolai,ccefor,cerfor,decw1,decw2,decw3,
     &     fcfrac,forrtf,klai,laitop,ldrmlt,leafdr,
     &     maxlai,maxldr,maxnp,sapk,swold,tfrtcn,tfrtcw,
     &     wdlig,woodb,wooddr

      save /parfs/
