
c               Copyright 1993 Colorado State University
c                       All Rights Reserved


      common/plot3/ acrcis(2),afbcis(2),afrcis(2),alvcis(2),alwcis(2),
     & crootc,croote(3),crtacc,crtcis(2),crtprd,eupprt(5,3),
     & fbrchc,fbrche(3),fbracc,fbrcis(2),fbrprd,
     & fcacc,fcmth(12),fcprd,forstg(3),
     & frootc,froote(3),frtacc,frtcis(2),frtprd,
     & frstc,frste(3),fsysc,fsyse(3),
     & rleavc,rleave(3),rlvacc,rlvcis(2),rlvprd,
     & rlwodc,rlwode(3),rlwacc,rlwcis(2),rlwprd,
     & sumrsp,tcrem,terem(3),
     & w1lig,w2lig,w3lig,w1mnr(3),w2mnr(3),w3mnr(3),wd1cis(2),
     & wd2cis(2),wd3cis(2),wood1c,wood2c,wood3c,woodc,wood1e(3),
     & wood2e(3),wood3e(3),woode(3)

      real acrcis,afbcis,afrcis,alvcis,alwcis,crootc,croote,crtacc,
     &     crtcis,crtprd,eupprt,fbrchc,fbrche,fbracc,fbrcis,fbrprd,
     &     fcacc,fcmth,fcprd,forstg,frootc,froote,frtacc,frtcis,
     &     frtprd,frstc,frste,fsysc,fsyse,rleavc,rleave,rlvacc,
     &     rlvcis,rlvprd,rlwodc,rlwode,rlwacc,rlwcis,rlwprd,sumrsp,
     &     tcrem,terem,w1lig,w2lig,w3lig,w1mnr,w2mnr,w3mnr,wd1cis,
     &     wd2cis,wd3cis,wood1c,wood2c,wood3c,woodc,wood1e,wood2e,
     &     wood3e,woode

      save /plot3/
