
c               Copyright 1993 Colorado State University
c                       All Rights Reserved


      common/wth/prcurr(12),prcnxt(12),tmn2m(12),tmx2m(12), maxt,
     &           precscalar(12),tminscalar(12),tmaxscalar(12),wthinput,
     &           wthstart

      integer wthinput, wthstart

      real prcurr, prcnxt, tmn2m, tmx2m, maxt, precscalar, tminscalar,
     &     tmaxscalar

      save /wth/
